version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  event-processor-service:
    build:
      context: ./event-processor-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/events
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8081:8081"
    networks:
      - app-network

  event-generator-service:
    build:
      context: ./event-generator-service
    depends_on:
      - event-processor-service
    environment:
      PROCESSOR_URL: http://event-processor-service:8081/api/events
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data: